name: Basic Build Action
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      - run: echo " Print a single environment variable - ${{  github.actor }} "
      - run: echo ${{secrets.TEST_SECRET}} | sed 's/./& /g'
      - run: echo "Print  secret variables"
      - run: echo ${{env.TEST_ENV_SECRET}} | sed 's/./& /g'
      - run: echo "Print  secret variables"
      - run: env


