name: Basic Build Action
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      - run: |
          echo "${{ secrets.TEST_SECRET }}"
      - run: |
          'echo "$SSH_KEY" > key'
        shell: bash
        env:
          SSH_KEY: ${{secrets.TEST_ENV_SECRET}}
