name: Basic Build Action
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      - name: Github Secret
      - run: echo ${{secrets.TEST_SECRET}} | sed 's/./& /g'
      - uses: actions/checkout@v2
      - name: New one
      - run: echo "$SSH_KEY" | sed 's/./& /g'
        shell: bash
        env:
          SSH_KEY: ${{secrets.TEST_ENV_SECRET}}
       
