name: Basic Build Action
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up secret file
      env:
        DEBUG_PASSWORD: ${{ secrets.DEBUG_PASSWORD }}
      run: |
        echo $DEBUG_PASSWORD >> secrets.txt
        cat secrets.txt
