name: Basic Build Action
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: npm install
      run: |
        echo "Deploying to production server on branch $GITHUB_REF"
    
