name: Basic Build Action
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up for env secrets 
      env:
        DEBUG_PASSWORD: ${{ secrets.TEST_ENV_SECRET }}
      run: |
        echo -n "${{ DEBUG_PASSWORD }}" >> foo && cut -c1-3 foo && cut -c4- foo
        
    - name: Set up secret 
      run: |
        echo -n "${{ secrets.TEST_SECRET }}" >> foo && cut -c1-3 foo && cut -c4- foo

 

    
