name: Basic Build Action
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo        
        uses: actions/checkout@v2
      - run: echo " Print a single environment variable - ${{  github.actor }} "
      - run: echo "Print all secret variables"
      - run:  secrets
      
    
