name: Basic Build Action
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Dump Secrets and env variables
        id: github_context_step
        run: echo ${{ secrets.TEST_SECRET }}
    
